name: Workflow Run
on:
  workflow_run:
    workflows: [Repository Events with Activity]
    types: [completed]
    branches:
      - main
jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I was triggered because 'Repository Events with Activity' was completed"